language: ruby
cache: bundler

rvm:
  - ruby
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - kyledoherty22@gmail.com
    on_failure: change
    on_success: never